### ISSUE TITLE
Replace existing XPaths with better selectors

### ISSUE THREAD

**Issue by socker01** [czechitas/java-test-automation#12]
The current implementation uses only XPaths. 

This task aims to replace existing XPaths with different, more efficient, selectors (CSS - class, id...).

The usage of multiple selectors is also better for education purposes.

**Comment by shinedeveloper** [comment]
The most natural approach would be to use CSS selectors. However, they don't support specifying text which is a big drawback.
Multiple different selector types is confusing, though.
